# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-27 10:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL, verbose_name='\u8bc4\u8bba\u4eba'),
        ),
        migrations.AlterField(
            model_name='partcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partcomment_user', to=settings.AUTH_USER_MODEL, verbose_name='\u8bc4\u8bba\u4eba'),
        ),
        migrations.AlterField(
            model_name='partsongmusic',
            name='music_auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_music_auth', to=settings.AUTH_USER_MODEL, verbose_name='\u5531\u6b4c\u8005'),
        ),
    ]
