# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-04 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0004_auto_20170428_0325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allsongmusic',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '\u5408\u5531\u6b4c\u66f2\u6570\u636e\u7ba1\u7406'},
        ),
        migrations.AlterModelOptions(
            name='partsongmusic',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '\u534a\u9996\u6b4c\u6570\u636e\u7ba1\u7406'},
        ),
        migrations.AddField(
            model_name='musicprofiel',
            name='style',
            field=models.IntegerField(blank=True, choices=[(0, 'MELODY'), (1, 'RAP')], null=True, verbose_name='\u6b4c\u66f2\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='musicprofiel',
            name='k_game',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6253\u5206\u6587\u4ef6'),
        ),
    ]
