# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 07:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dao', '0005_auto_20170504_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALLMusicPraise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_praise', models.BooleanField(verbose_name='\u662f\u5426\u8d5e\u8fc7')),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': '\u5408\u5531\u6b4c\u66f2\u70b9\u8d5e\u7ba1\u7406',
            },
        ),
        migrations.AlterField(
            model_name='allsongmusic',
            name='voice_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u97f3\u9891\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='allmusicpraise',
            name='music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allmusic_praise_user', to='dao.AllSongMusic', verbose_name='\u6240\u5c5e\u6b4c\u66f2'),
        ),
        migrations.AddField(
            model_name='allmusicpraise',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parise_user', to=settings.AUTH_USER_MODEL, verbose_name='\u8d5e\u7684\u4eba'),
        ),
    ]
