# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0006_auto_20170508_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_user', to=settings.AUTH_USER_MODEL, verbose_name='\u8bc4\u8bba\u4eba'),
        ),
    ]
