# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-10 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0007_auto_20170508_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allcomment',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '\u5408\u5531\u6b4c\u66f2\u8bc4\u8bba\u7ba1\u7406'},
        ),
        migrations.AlterModelOptions(
            name='musicprofiel',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '\u6b4c\u66f2\u4fe1\u606f\u5173\u7cfb'},
        ),
        migrations.AlterModelOptions(
            name='partcomment',
            options={'ordering': ['-created_at'], 'verbose_name_plural': '\u534a\u9996\u6b4c\u8bc4\u8bba\u7ba1\u7406'},
        ),
        migrations.RenameField(
            model_name='musicprofiel',
            old_name='snger_name',
            new_name='singer_name',
        ),
    ]
