# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-10 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0008_auto_20170510_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='allsongmusic',
            name='music_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='music_pro', to='dao.MusicProfiel', verbose_name='\u6b4c\u66f2\u4fe1\u606f'),
        ),
    ]
