# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-11 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0009_allsongmusic_music_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicprofiel',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5220\u9664'),
        ),
    ]
