# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0010_auto_20170511_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicprofiel',
            name='view_times',
        ),
        migrations.AddField(
            model_name='musicprofiel',
            name='sing_count',
            field=models.BigIntegerField(default=0, verbose_name='\u88ab\u5408\u5531\u6b21\u6570'),
        ),
        migrations.AddField(
            model_name='musicprofiel',
            name='view_count',
            field=models.BigIntegerField(default=0, verbose_name='\u70b9\u51fb\u6b21\u6570'),
        ),
    ]
