# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0011_auto_20170512_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicprofiel',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e0a\u7ebf'),
        ),
    ]
