# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0012_musicprofiel_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicprofiel',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6b4c\u66f2\u5c01\u9762\u56fe\u7247'),
        ),
    ]
