# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0014_auto_20170512_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allsongmusic',
            name='voice_url',
        ),
        migrations.AlterField(
            model_name='allsongmusic',
            name='vedio',
            field=models.CharField(max_length=200, verbose_name='\u5408\u6210\u540e\u89c6\u9891'),
        ),
        migrations.AlterField(
            model_name='partsongmusic',
            name='auth_vedio',
            field=models.CharField(max_length=200, verbose_name='\u5531\u6b4c\u8005\u539f\u59cb\u89c6\u9891'),
        ),
        migrations.AlterField(
            model_name='partsongmusic',
            name='voice_url',
            field=models.CharField(max_length=200, verbose_name='\u4e0e\u4f34\u594f\u5408\u6210\u540e\u97f3\u9891\u5730\u5740'),
        ),
    ]
