# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0016_partsongmusic_peitain_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsongmusic',
            name='music_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='music_part', to='dao.MusicProfiel', verbose_name='\u6b4c\u66f2\u6570\u636e'),
        ),
    ]
