# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0017_auto_20170515_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsongmusic',
            name='peitain_to',
            field=models.IntegerField(blank=True, choices=[(0, 'PART_A'), (1, 'PART_B')], null=True, verbose_name='\u5c5e\u4e8e\u6b4c\u66f2\u54ea\u534a\u90e8\u5206'),
        ),
    ]
