# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0018_auto_20170515_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partsongmusic',
            old_name='peitain_to',
            new_name='part',
        ),
    ]
