# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-16 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0020_partsongmusic_auth_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicprofiel',
            name='style',
            field=models.IntegerField(blank=True, choices=[(0, 'MELODY'), (1, 'RAP'), (2, 'LOVE')], null=True, verbose_name='\u6b4c\u66f2\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='partsongmusic',
            name='auth_photo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5531\u6b4c\u4eba\u663e\u793a\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='partsongmusic',
            name='auth_vedio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5531\u6b4c\u8005\u539f\u59cb\u89c6\u9891'),
        ),
        migrations.AlterField(
            model_name='partsongmusic',
            name='auth_voice',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5531\u6b4c\u8005\u539f\u59cb\u97f3\u9891'),
        ),
        migrations.AlterField(
            model_name='partsongmusic',
            name='voice_url',
            field=models.CharField(max_length=200, verbose_name='\u4e0e\u4f34\u594f\u5408\u6210\u540e\u89c6\u9891\u5730\u5740'),
        ),
    ]
