# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-01 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0024_auto_20170524_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='allsongmusic',
            name='hour_count',
            field=models.BigIntegerField(default=0, verbose_name='\u6bcf\u5c0f\u65f6\u89c2\u770b\u6b21\u6570'),
        ),
    ]
