# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-19 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0025_allsongmusic_hour_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allsongmusic',
            options={'ordering': ['-rank', '-view_count', '-created_at'], 'verbose_name_plural': '\u5408\u5531\u6b4c\u66f2\u6570\u636e\u7ba1\u7406'},
        ),
        migrations.AddField(
            model_name='singer',
            name='uid',
            field=models.IntegerField(default=1, verbose_name='\u4e0a\u4f20\u6570\u636e\u552f\u4e00\u6807\u8bc6'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='singer_name',
            field=models.CharField(max_length=200, verbose_name='\u6b4c\u624b\u540d'),
        ),
    ]
