# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-19 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0026_auto_20170619_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='uid',
            field=models.IntegerField(unique=True, verbose_name='\u4e0a\u4f20\u6570\u636e\u552f\u4e00\u6807\u8bc6'),
        ),
    ]
