# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-19 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0027_auto_20170619_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singer',
            options={'ordering': ['-rank'], 'verbose_name_plural': '\u6b4c\u624b\u7ba1\u7406'},
        ),
        migrations.RemoveField(
            model_name='musicprofiel',
            name='singer',
        ),
        migrations.AddField(
            model_name='musicprofiel',
            name='singer',
            field=models.ManyToManyField(db_index=True, related_name='singer_info', to='dao.Singer'),
        ),
    ]
