# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-20 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0028_auto_20170619_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicprofiel',
            options={'ordering': ['-rank'], 'verbose_name_plural': '\u6b4c\u66f2\u4fe1\u606f\u5173\u7cfb'},
        ),
        migrations.AlterField(
            model_name='musicprofiel',
            name='accompany',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4f34\u594f\u6587\u4ef6'),
        ),
        migrations.AlterField(
            model_name='musicprofiel',
            name='lyrics',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6b4c\u8bcd\u6587\u4ef6'),
        ),
    ]
