# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-20 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0029_auto_20170620_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicprofiel',
            name='uid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6b4c\u66f2\u552f\u4e00\u6807\u8bc6'),
        ),
    ]
