# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-28 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0034_auto_20170628_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicprofiel',
            name='uid',
            field=models.CharField(max_length=200, unique=True, verbose_name='\u6b4c\u66f2\u552f\u4e00\u6807\u8bc6'),
        ),
    ]
