# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-04 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0035_auto_20170628_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allmusicpraise',
            name='is_praise',
        ),
    ]
