# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-04 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0036_remove_allmusicpraise_is_praise'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.IntegerField(blank=True, choices=[(0, 'lyc_error'), (1, 'GEQUCUOWU')], null=True, verbose_name='\u9519\u8bef\u7c7b\u578b')),
                ('is_solve', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5904\u7406\u5b8c\u6bd5')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name_plural': '\u6b4c\u66f2\u4e3e\u62a5\u7ba1\u7406',
            },
        ),
        migrations.AlterModelOptions(
            name='musicprofiel',
            options={'verbose_name_plural': '\u6b4c\u66f2\u4fe1\u606f\u5173\u7cfb'},
        ),
        migrations.AddField(
            model_name='reportsong',
            name='report_music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_music', to='dao.MusicProfiel', verbose_name='\u4e3e\u62a5\u7684\u6b4c\u66f2'),
        ),
    ]
