# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-17 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0037_auto_20170704_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allsongmusic',
            options={'ordering': ['-rank', '-created_at'], 'verbose_name_plural': '\u5408\u5531\u6b4c\u66f2\u6570\u636e\u7ba1\u7406'},
        ),
        migrations.AlterField(
            model_name='allsongmusic',
            name='music_auth_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_music_part', to='dao.PartSongMusic', verbose_name='\u53d1\u5e03\u6b4c\u66f2\u8005\u90e8\u5206'),
        ),
        migrations.AlterField(
            model_name='reportsong',
            name='report_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Music Quality'), (1, 'Lyric Quality'), (2, 'Partner Complaint')], null=True, verbose_name='\u9519\u8bef\u7c7b\u578b'),
        ),
    ]
