# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-17 08:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dao', '0039_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutyouNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6807\u9898')),
                ('text', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5185\u5bb9')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u94fe\u63a5')),
                ('post', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u76f8\u5173\u4f5c\u54c1ID')),
                ('type', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u7c7b\u578b')),
                ('is_read', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u8bfb')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_user_y_notifaction', to=settings.AUTH_USER_MODEL, verbose_name='\u88ab\u6267\u884c\u6d3b\u52a8\u7684\u4eba')),
                ('all_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_y_notifaction', to='dao.AllSongMusic', verbose_name='\u76f8\u5173\u4f5c\u54c1')),
                ('from_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user_y_notifaction', to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u9001\u8005')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_y_notifaction', to=settings.AUTH_USER_MODEL, verbose_name='\u63a5\u53d7\u6d88\u606f\u8005')),
            ],
            options={
                'ordering': ('-created_at',),
                'verbose_name_plural': '\u6d88\u606f\u7ba1\u7406',
            },
        ),
    ]
