# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-18 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0040_aboutyounotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutyounotification',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'FOLLOWING'), (1, 'COMMENT'), (2, 'PRAISE')], null=True, verbose_name='\u6d88\u606f\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'INVITED'), (1, 'JOIN')], null=True, verbose_name='\u6d88\u606f\u7c7b\u578b'),
        ),
    ]
