# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-18 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0041_auto_20170718_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcomment',
            old_name='content',
            new_name='text',
        ),
    ]
