# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-18 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0043_auto_20170718_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcomment',
            old_name='user',
            new_name='owner',
        ),
    ]
