# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-21 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0044_auto_20170718_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u65b0\u5efa\u65f6\u95f4'),
        ),
    ]
