# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-25 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0045_auto_20170721_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicprofiel',
            name='bucket_accompany_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4f34\u594f\u6587\u4ef6bucket\u7684key'),
        ),
        migrations.AddField(
            model_name='musicprofiel',
            name='bucket_accompany_mp4_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='mp4\u4f34\u594f\u6587\u4ef6bucket\u7684key'),
        ),
        migrations.AddField(
            model_name='musicprofiel',
            name='bucket_accompany_mp4_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='mp4\u4f34\u594f\u6587\u4ef6BUCKET\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='musicprofiel',
            name='bucket_accompany_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4f34\u594f\u6587\u4ef6BUCKET\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='musicprofiel',
            name='bucket_image_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6b4c\u66f2\u56fe\u7247\u6587\u4ef6bucket\u7684key'),
        ),
        migrations.AddField(
            model_name='musicprofiel',
            name='bucket_image_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6b4c\u66f2\u56fe\u7247\u6587\u4ef6BUCKET\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='musicprofiel',
            name='bucket_lyrics_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6b4c\u8bcd\u6587\u4ef6bucket\u7684key'),
        ),
        migrations.AddField(
            model_name='musicprofiel',
            name='bucket_lyrics_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6b4c\u8bcd\u6587\u4ef6BUCKET\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='musicprofiel',
            name='bucket_original_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u539f\u5531\u6587\u4ef6bucket\u7684key'),
        ),
        migrations.AddField(
            model_name='musicprofiel',
            name='bucket_original_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u539f\u5531\u6587\u4ef6BUCKET\u540d\u79f0'),
        ),
    ]
