# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-25 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0046_auto_20170725_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='allsongmusic',
            name='bucket_photo_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u622a\u56fe\u6587\u4ef6bucket\u7684key'),
        ),
        migrations.AddField(
            model_name='allsongmusic',
            name='bucket_photo_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u622a\u56fe\u6587\u4ef6BUCKET\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='allsongmusic',
            name='bucket_vedio_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5408\u6210\u89c6\u9891\u6587\u4ef6bucket\u7684key'),
        ),
        migrations.AddField(
            model_name='allsongmusic',
            name='bucket_vedio_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5408\u6210\u89c6\u9891\u6587\u4ef6BUCKET\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='partsongmusic',
            name='bucket_caivedio_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u88c1\u526a\u89c6\u9891\u6587\u4ef6bucket\u7684key'),
        ),
        migrations.AddField(
            model_name='partsongmusic',
            name='bucket_caivedio_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u88c1\u526a\u89c6\u9891\u6587\u4ef6BUCKET\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='partsongmusic',
            name='bucket_photo_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u622a\u56fe\u6587\u4ef6bucket\u7684key'),
        ),
        migrations.AddField(
            model_name='partsongmusic',
            name='bucket_photo_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u622a\u56fe\u6587\u4ef6BUCKET\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='partsongmusic',
            name='bucket_vedio_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5408\u6210\u89c6\u9891\u6587\u4ef6bucket\u7684key'),
        ),
        migrations.AddField(
            model_name='partsongmusic',
            name='bucket_vedio_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5408\u6210\u89c6\u9891\u6587\u4ef6BUCKET\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='allsongmusic',
            name='photo',
            field=models.CharField(max_length=200, verbose_name='\u663e\u793a\u56fe\u7247\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='allsongmusic',
            name='vedio',
            field=models.CharField(max_length=200, verbose_name='\u5408\u6210\u540e\u89c6\u9891\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='partsongmusic',
            name='auth_photo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5531\u6b4c\u4eba\u663e\u793a\u56fe\u7247\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='partsongmusic',
            name='auth_vedio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u88c1\u526a\u540e\u89c6\u9891\u52a0\u539f\u97f3\u5730\u5740'),
        ),
    ]
