# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-25 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0047_auto_20170725_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allsongmusic',
            old_name='bucket_photo_key',
            new_name='bucket_all_photo_key',
        ),
        migrations.RenameField(
            model_name='allsongmusic',
            old_name='bucket_photo_name',
            new_name='bucket_all_photo_name',
        ),
        migrations.RenameField(
            model_name='allsongmusic',
            old_name='bucket_vedio_key',
            new_name='bucket_all_vedio_key',
        ),
        migrations.RenameField(
            model_name='allsongmusic',
            old_name='bucket_vedio_name',
            new_name='bucket_all_vedio_name',
        ),
        migrations.RenameField(
            model_name='partsongmusic',
            old_name='bucket_photo_key',
            new_name='bucket_part_photo_key',
        ),
        migrations.RenameField(
            model_name='partsongmusic',
            old_name='bucket_photo_name',
            new_name='bucket_part_photo_name',
        ),
        migrations.RenameField(
            model_name='partsongmusic',
            old_name='bucket_vedio_key',
            new_name='bucket_part_vedio_key',
        ),
        migrations.RenameField(
            model_name='partsongmusic',
            old_name='bucket_vedio_name',
            new_name='bucket_part_vedio_name',
        ),
        migrations.AlterField(
            model_name='partsongmusic',
            name='auth_photo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u622a\u56fe\u6587\u4ef6\u56fe\u7247\u5730\u5740'),
        ),
    ]
