# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-25 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0048_auto_20170725_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicprofiel',
            name='accompany_mp4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MP4\u4f34\u594f\u6587\u4ef6'),
        ),
    ]
