# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-07 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0050_auto_20170801_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicprofiel',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='\u624b\u52a8\u6392\u5e8f'),
        ),
        migrations.AlterField(
            model_name='musicprofiel',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='\u70ed\u95e8\u6392\u5e8f'),
        ),
    ]
