# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-10 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0052_auto_20170808_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allsongmusic',
            name='bucket_all_photo_key',
        ),
        migrations.RemoveField(
            model_name='allsongmusic',
            name='bucket_all_photo_name',
        ),
    ]
