# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-11 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0053_auto_20170810_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='partsongmusic',
            name='part_vedio_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u89c6\u9891\u5730\u5740'),
        ),
    ]
