# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-17 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0054_partsongmusic_part_vedio_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutyounotification',
            options={'ordering': ('-created_at',), 'verbose_name_plural': '\u5173\u4e8e\u4f60\u6d88\u606f\u7ba1\u7406'},
        ),
        migrations.AlterField(
            model_name='aboutyounotification',
            name='type',
            field=models.IntegerField(blank=True, choices=[(3, 'FOLLOWING'), (4, 'LIKE'), (5, 'COMMENT')], null=True, verbose_name='\u6d88\u606f\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'INVITED'), (2, 'JOIN')], null=True, verbose_name='\u6d88\u606f\u7c7b\u578b'),
        ),
    ]
