# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-17 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0055_auto_20170817_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='partsongmusic',
            name='one_bucket_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u89c6\u9891\u4f34\u594f\u5e72\u58f0\u5408\u6210\u540e\u89c6\u9891key'),
        ),
        migrations.AddField(
            model_name='partsongmusic',
            name='one_bucket_name',
            field=models.CharField(default='duetin-one', max_length=200, verbose_name='\u89c6\u9891\u4f34\u594f\u5e72\u58f0\u5408\u6210\u540e\u89c6\u9891bucket'),
        ),
        migrations.AlterField(
            model_name='partsongmusic',
            name='part_vedio_bucket_name',
            field=models.CharField(default='duetin-part', max_length=200, verbose_name='\u5408\u6210\u89c6\u56fe\u7247\u6587\u4ef6BUCKET\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='partsongmusic',
            name='part_vedio_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5408\u6210\u89c6\u9891\u56fe\u7247\u6587\u4ef6bucket\u7684key'),
        ),
    ]
