# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-17 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0057_auto_20170817_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsongmusic',
            name='one_bucket_name',
            field=models.CharField(default='duetin-part-one', max_length=200, verbose_name='\u89c6\u9891\u4f34\u594f\u5e72\u58f0\u5408\u6210\u540e\u89c6\u9891bucket'),
        ),
    ]
