# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-15 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0058_auto_20170817_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='\u7528\u6237ID')),
                ('username', models.CharField(max_length=100, verbose_name='\u7528\u6237\u540d')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u6807\u9898')),
                ('music_id', models.BigIntegerField(verbose_name='\u6b4c\u66f2ID')),
                ('participant_id', models.BigIntegerField(blank=True, null=True, verbose_name='\u5bf9\u5531\u90e8\u5206partID')),
                ('part_to', models.BigIntegerField(verbose_name='\u8981\u5531\u7684\u90e8\u52060\u6216\u80051')),
                ('is_enable', models.BigIntegerField(default=1, verbose_name='\u662f\u5426\u5141\u8bb8\u52a0\u5165')),
                ('ts', models.BigIntegerField(verbose_name='TS\u503c')),
                ('trim', models.IntegerField(verbose_name='\u9700\u8981\u622a\u53d6\u7684\u65f6\u95f4')),
                ('invite', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u9080\u8bf7\u5217\u8868')),
                ('aac_key_name', models.CharField(max_length=300, verbose_name='\u97f3\u9891key')),
                ('mp4_key_name', models.CharField(max_length=300, verbose_name='\u89c6\u9891KEY')),
                ('banzou_key_name', models.CharField(max_length=300, verbose_name='\u4f34\u594fkey')),
                ('participant_part_one_mp4', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u5408\u5531one\u89c6\u9891key')),
                ('part_jpg_key_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u7b2c\u4e00\u6b21\u5531\u9759\u6001\u56fe\u7247key')),
                ('is_ok', models.BooleanField(default=False, verbose_name='\u662f\u5426\u6267\u884c\u6210\u529f')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('complate_at', models.DateTimeField(blank=True, null=True, verbose_name='\u6267\u884c\u5b8c\u6bd5\u65f6\u95f4')),
            ],
            options={
                'verbose_name_plural': '\u5408\u6210\u4efb\u52a1\u7ba1\u7406',
            },
        ),
    ]
