# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-30 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0060_auto_20170919_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='partsongmusic',
            name='part_user_img_bucket',
            field=models.CharField(blank=True, default='duetin-android-image', max_length=200, null=True, verbose_name='\u65e0\u89c6\u9891\u5408\u6210\u56fe\u7247bucket'),
        ),
        migrations.AddField(
            model_name='partsongmusic',
            name='part_user_img_key',
            field=models.CharField(blank=True, default='part_user_img.jpg', max_length=200, null=True, verbose_name='\u65e0\u89c6\u9891\u5408\u6210\u56fe\u7247key'),
        ),
    ]
