# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-13 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0062_auto_20171010_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='allsongmusic',
            name='rating_scale',
            field=models.IntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], null=True, verbose_name='\u8bc4\u5206\u7b49\u7ea7'),
        ),
    ]
