# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-23 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0063_allsongmusic_rating_scale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allsongmusic',
            options={'ordering': ['-rank', '-view_count_rank', '-created_at'], 'verbose_name_plural': '\u5408\u5531\u6b4c\u66f2\u6570\u636e\u7ba1\u7406'},
        ),
        migrations.AlterField(
            model_name='musicprofiel',
            name='style',
            field=models.IntegerField(blank=True, choices=[(0, 'MELODY'), (1, 'RAP'), (2, 'Rap&Melody'), (9, 'Undefined')], null=True, verbose_name='\u6b4c\u66f2\u7c7b\u578b'),
        ),
    ]
