# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-24 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0065_exceptioncase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'JOIN'), (2, 'INVITED')], null=True, verbose_name='\u6d88\u606f\u7c7b\u578b'),
        ),
    ]
