# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-31 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0066_auto_20171024_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_brand', models.CharField(max_length=300, verbose_name='\u624b\u673a\u54c1\u724c')),
                ('mobile_name', models.CharField(max_length=300, verbose_name='\u624b\u673a\u540d\u79f0')),
                ('mobile_version', models.CharField(max_length=300, verbose_name='\u624b\u673a\u578b\u53f7')),
                ('mobile_edition', models.CharField(max_length=300, verbose_name='\u624b\u673a\u56fa\u4ef6\u7248\u672c')),
                ('mobile_yj_name', models.CharField(max_length=300, verbose_name='\u786c\u4ef6\u540d\u79f0')),
                ('default_time', models.IntegerField(default=0, verbose_name='\u9ed8\u8ba4\u5ef6\u8fdf\u6beb\u79d2\u6570')),
                ('delay_time', models.IntegerField(default=0, verbose_name='\u5ef6\u8fdf\u6beb\u79d2\u6570')),
            ],
            options={
                'verbose_name_plural': '\u624b\u673a\u578b\u53f7\u7248\u672c',
            },
        ),
    ]
