# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-10 07:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dao', '0067_mobileversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name='\u5bf9\u8c61ID')),
                ('object_rep', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u5bf9\u8c61\u540d')),
                ('type', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u7c7b\u578b')),
                ('change_message', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u64cd\u4f5c\u8be6\u60c5')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u64cd\u4f5c\u4eba')),
            ],
            options={
                'verbose_name_plural': '\u7528\u6237\u64cd\u4f5c\u65e5\u5fd7',
            },
        ),
        migrations.AlterField(
            model_name='musicprofiel',
            name='music_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u6b4c\u66f2\u540d'),
        ),
        migrations.AlterField(
            model_name='musicprofiel',
            name='uid',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='\u6b4c\u66f2\u552f\u4e00\u6807\u8bc6'),
        ),
    ]
