# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-10 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0068_auto_20171110_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allsongmusic',
            options={'verbose_name_plural': '\u5408\u5531\u6b4c\u66f2\u6570\u636e\u7ba1\u7406'},
        ),
    ]
