# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-13 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0069_auto_20171110_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicprofiel',
            name='top_rank',
            field=models.IntegerField(default=0, verbose_name='top50\u6392\u5e8f'),
        ),
        migrations.AlterField(
            model_name='musicprofiel',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='\u70ed\u5ea6\u6392\u5e8f'),
        ),
    ]
