# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-16 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0070_auto_20171113_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='allsongmusic',
            name='is_recommend_rank',
            field=models.IntegerField(default=0, verbose_name='\u63a8\u8350\u7ed9\u65b0\u7528\u6237\u6392\u5e8f'),
        ),
    ]
