# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-17 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0072_partsongmusic_rating_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='partsongmusic',
            name='photo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u663e\u793a\u56fe\u7247\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='partsongmusic',
            name='vedio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5408\u6210\u540e\u89c6\u9891\u5730\u5740'),
        ),
    ]
