# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-29 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0076_allsongmusic_share_jpg_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='uid',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='\u6267\u884ciD'),
        ),
    ]
