# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-04 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0079_auto_20171229_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='all_music_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u4f5c\u54c1ID'),
        ),
        migrations.AddField(
            model_name='postdata',
            name='all_music_image',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='\u4f5c\u54c1GIF'),
        ),
    ]
