# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-08 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0080_auto_20180104_1921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobileVersion',
        ),
    ]
