# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-22 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0081_delete_mobileversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='bmp_ts',
            field=models.IntegerField(default=8, verbose_name='\u622a\u56fe\u65f6\u95f4\u70b9\u79d2'),
        ),
        migrations.AddField(
            model_name='postdata',
            name='reverberation_type',
            field=models.IntegerField(default=0, verbose_name='\u6df7\u54cd\u6548\u679c'),
        ),
    ]
