# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-26 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0082_auto_20180122_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdata',
            name='reverberation',
            field=models.IntegerField(default=0, verbose_name='\u6df7\u54cd\u6548\u679c'),
        ),
    ]
