# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-26 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0083_postdata_reverberation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdata',
            name='reverberation',
        ),
    ]
