# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-26 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0085_auto_20180127_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdata',
            name='part_id',
        ),
    ]
