# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-02-06 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0086_remove_postdata_part_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMusicCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u7c7b\u522b\u540d\u79f0')),
                ('rank', models.IntegerField(default=0, verbose_name='\u6392\u5e8f')),
                ('is_online', models.BooleanField(default=True, verbose_name='\u662f\u5426\u663e\u793a')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-rank'],
                'verbose_name_plural': '\u5408\u6210\u6b4c\u66f2\u5206\u7c7b\u7ba1\u7406',
            },
        ),
        migrations.AddField(
            model_name='allsongmusic',
            name='all_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_category_video', to='dao.AllMusicCategory', verbose_name='\u5206\u7c7b'),
        ),
    ]
