# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-21 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0088_songexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicprofiel',
            name='time_a',
            field=models.IntegerField(default=0, verbose_name='\u6b4c\u66f2A\u5f00\u59cb\u5531\u7684\u65f6\u95f4\u70b9'),
        ),
        migrations.AddField(
            model_name='musicprofiel',
            name='time_b',
            field=models.IntegerField(default=0, verbose_name='\u6b4c\u66f2B\u5f00\u59cb\u5531\u7684\u65f6\u95f4\u70b9'),
        ),
    ]
