# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-13 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0089_auto_20180321_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='allmusiccategory',
            name='id_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5370\u5c3c\u7c7b\u522b\u540d\u79f0'),
        ),
    ]
