# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-28 09:59
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='\u6635\u79f0')),
                ('resume', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u4e2a\u4eba\u4ecb\u7ecd')),
                ('sex', models.IntegerField(blank=True, choices=[(9, b'None'), (0, b'MAN'), (1, b'WOMEN')], default=9, null=True, verbose_name='\u6027\u522b')),
                ('picture', models.CharField(default=b'', max_length=2000, verbose_name='\u5934\u50cf\u5730\u5740')),
                ('phone', models.CharField(blank=True, default=b'', max_length=64, verbose_name='\u7535\u8bdd')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='\u5220\u9664\u65e5\u671f')),
                ('is_enable', models.BooleanField(default=True, verbose_name='\u662f\u5426\u5141\u8bb8\u767b\u5f55')),
                ('is_delete', models.BooleanField(default=False, verbose_name='\u662f\u5426\u88ab\u5220\u9664')),
                ('is_email_val', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u7ecf\u90ae\u4ef6\u9a8c\u8bc1')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(blank=True, null=True)),
                ('blacker_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '\u9ed1\u540d\u5355\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Fans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('follower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fans_follower', to=settings.AUTH_USER_MODEL, verbose_name='\u88ab\u5173\u6ce8\u65b9')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fans_owner', to=settings.AUTH_USER_MODEL, verbose_name='\u4e3b\u52a8\u5173\u6ce8\u65b9')),
            ],
            options={
                'verbose_name_plural': '\u597d\u53cb\u5173\u7cfb\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='FollowerNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6807\u9898')),
                ('text', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5185\u5bb9')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u94fe\u63a5')),
                ('post', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u76f8\u5173\u4f5c\u54c1ID')),
                ('type', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u7c7b\u578b')),
                ('is_read', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u8bfb')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_user_f_notifaction', to=settings.AUTH_USER_MODEL, verbose_name='\u88ab\u6267\u884c\u6d3b\u52a8\u7684\u4eba')),
                ('from_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user_f_notifaction', to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u9001\u8005')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_f_notifaction', to=settings.AUTH_USER_MODEL, verbose_name='\u63a5\u53d7\u6d88\u606f\u8005')),
            ],
            options={
                'ordering': ('-created_at',),
                'verbose_name_plural': '\u6d88\u606f\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='NotificationApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6807\u9898')),
                ('text', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5185\u5bb9')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u94fe\u63a5')),
                ('post', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u76f8\u5173\u4f5c\u54c1ID')),
                ('type', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u7c7b\u578b')),
                ('is_read', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u8bfb')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user_notifaction', to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u9001\u8005')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_notifaction', to=settings.AUTH_USER_MODEL, verbose_name='\u63a5\u53d7\u8005')),
            ],
            options={
                'ordering': ('-created_at',),
                'verbose_name_plural': '\u6d88\u606f\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='RegisterEmailToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic_url', models.CharField(max_length=64, null=True, unique=True)),
                ('entry_token', models.CharField(blank=True, max_length=64)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('expire_time', models.DateTimeField(auto_now_add=True)),
                ('is_activate', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResetPasswordToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic_url', models.CharField(max_length=64, null=True, unique=True)),
                ('entry_token', models.CharField(blank=True, max_length=64)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('expire_time', models.DateTimeField(auto_now_add=True)),
                ('is_activate', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6807\u9898')),
                ('context', models.CharField(max_length=200, verbose_name='\u5185\u5bb9')),
                ('is_read', models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u8bfb')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_suggest', to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u9001\u8005')),
            ],
            options={
                'verbose_name_plural': '\u5efa\u8bae\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationsCount',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('unread_count', models.IntegerField(default=0)),
            ],
        ),
    ]
