# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-17 07:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationapp',
            name='from_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user_notifaction1', to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u9001\u8005'),
        ),
        migrations.AlterField(
            model_name='notificationapp',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_notifaction1', to=settings.AUTH_USER_MODEL, verbose_name='\u63a5\u53d7\u8005'),
        ),
    ]
