# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-15 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_auto_20170717_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u751f\u65e5'),
        ),
    ]
