# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-22 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0003_user_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5730\u533a'),
        ),
    ]
