# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-13 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0004_user_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5c5e\u4e8e\u5927V'),
        ),
    ]
