# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-23 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0005_user_is_important'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_operate_list', '\u8fd0\u8425\u7ba1\u7406'),), 'verbose_name_plural': '\u7528\u6237\u4fe1\u606f'},
        ),
    ]
