# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-16 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0007_auto_20171031_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_recommend',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u63a8\u8350\u7ed9\u65b0\u7528\u6237'),
        ),
    ]
