# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-28 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0008_user_is_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture_bucket_name',
            field=models.CharField(default=b'duetin-user-tx', max_length=200, verbose_name='\u5934\u50cf\u6587\u4ef6BUCKET\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='user',
            name='picture_key_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5934\u50cf\u6587\u4ef6bucket\u7684key'),
        ),
    ]
