# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-01-08 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0009_auto_20171228_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_brand', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u624b\u673a\u54c1\u724cManufacturer')),
                ('mobile_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u624b\u673a\u540d\u79f0name')),
                ('mobile_version', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u624b\u673a\u578b\u53f7Model')),
                ('mobile_edition', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u624b\u673a\u56fa\u4ef6\u7248\u672cOS')),
                ('mobile_yj_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='\u786c\u4ef6\u540d\u79f0deviceName')),
                ('default_time', models.IntegerField(default=300, verbose_name='\u9ed8\u8ba4\u5ef6\u8fdf\u6beb\u79d2\u6570')),
                ('delay_time', models.IntegerField(default=0, verbose_name='\u5ef6\u8fdf\u6beb\u79d2\u6570')),
            ],
            options={
                'verbose_name_plural': '\u624b\u673a\u578b\u53f7\u7248\u672c',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usermoblie', to='app_auth.MobileVersion', verbose_name='\u7528\u6237\u5bf9\u5e94\u624b\u673a\u4fe1\u606f'),
        ),
    ]
