# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-12 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0010_auto_20180108_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='users_rank',
            field=models.IntegerField(default=0, verbose_name='\u6dfb\u52a0\u7528\u6237,\u8fd0\u8425,\u663e\u793a\u7528\u6237\u6392\u5e8f'),
        ),
    ]
