# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-13 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0011_user_users_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ins\u767b\u5f55code'),
        ),
    ]
