# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-14 09:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0012_user_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsBinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5e94\u7528\u540d\u79f0')),
                ('uid', models.BigIntegerField(unique=True, verbose_name='\u5e94\u7528\u7528\u6237UID')),
                ('access_token', models.CharField(blank=True, max_length=250, null=True, verbose_name='access_token')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5173\u8054\u7528\u6237')),
            ],
            options={
                'verbose_name_plural': '\u7ed1\u5b9ains\u8d26\u53f7\u4fe1\u606f',
            },
        ),
    ]
