# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-20 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0014_user_recommend_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='\u5934\u50cf\u5730\u5740'),
        ),
    ]
