# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-20 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0015_auto_20180320_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='users_rank',
            new_name='add_user_rank',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='recommend_rank',
            new_name='new_user_rank',
        ),
    ]
