# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-27 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0016_auto_20180320_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileversion',
            name='error_count',
            field=models.IntegerField(default=0, verbose_name='\u68c0\u6d4b\u5931\u8d25\u6b21\u6570'),
        ),
    ]
