# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-04 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0018_auto_20180327_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_key_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u80cc\u666f\u56fe\u7247\u7684key'),
        ),
    ]
