# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-09 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0019_user_background_key_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='insbinding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
