# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-10 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0020_insbinding_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture_key_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5934\u50cf\u6587\u4ef6bucket\u7684key'),
        ),
    ]
