# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-13 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0022_auto_20180413_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_birth',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='\u751f\u65e5\u65f6\u95f4\u6233'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u751f\u65e5'),
        ),
    ]
